# Gradle Configuration -- DO NOT TOUCH THESE VALUES.
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx2G
loom.ignoreDependencyLoomVersionValidation=true

# gradle.properties file -- CHANGE THE VALUES STARTING WITH `mod.*` AND REMOVE THIS COMMENT.

# Sets the name of your mod.
mod.name=OneConfigBootstrap
# Sets the ID of your mod that mod loaders use to recognize it.
mod.id=oneconfigbootstrap
# Sets the Maven group ID of your mod. This is effectively unused but is good practice to set regardless.
mod.group=org.polyfrost

mod.version=1.0.0-alpha.116
oneconfig.loader=1.1.0-alpha.48
oneconfig.omnicore=0.37.0
oneconfig.textile=0.12.0
oneconfig.flk=1.12.2+kotlin.2.0.20