# Build Workflow

name: Build with Gradle

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: always
          add-job-summary: always
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          gradle-home-cache-cleanup: true
          validate-wrappers: true
          cache-read-only: ${{ github.ref != 'refs/heads/v1' }}

      - uses: actions/cache@v4
        with:
          path: |
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: versions/**/build/libs
